:art: activate virtualenv in bootstrap

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -62,7 +62,7 @@ do_progress_quiet() {
 }
 
 
-
+# Install homebrew packages if running on macOS
 if [[ -f "Brewfile" ]] && [[ "$(uname -s)" = "Darwin" ]]; then
   [[ $(which brew) ]] || die "Homebrew is not installed. See https://brew.sh"
   brew bundle check >/dev/null 2>&1  || {
@@ -71,41 +71,47 @@ if [[ -f "Brewfile" ]] && [[ "$(uname -s)" = "Darwin" ]]; then
   }
 fi
 
+# Python: Install & Activate python virtualenv
+if [[ ! "${CI}" = "true" && -f "./setup.py" ]]; then
+  # Only install & activate the virtualenv if not already in one
+  if [[ -z "${VIRTUAL_ENV}" ]]; then
 
-if [[ ! "${CI}" = "true" && -f "./setup.py" && ! $(which virtualenv) ]]; then
-  if [[ -z "$(which virtualenv)" ]]; then
-    if [[ -f "Brewfile" ]] && [[ "$(uname -s)" = "Darwin" ]]; then
-      do_progress_quiet "Unlinking homebrew python (just-in-case)" \
-        brew unlink python
-      do_progress_quiet "Relinking homebrew python" \
-        brew link python
+    if [[ ! $(which virtualenv) ]]; then
+      # macOS needs a little extra love
+      if [[ -f "Brewfile" ]] && [[ "$(uname -s)" = "Darwin" ]]; then
+        do_progress_quiet "Unlinking homebrew python (just-in-case)" \
+          brew unlink python
+        do_progress_quiet "Relinking homebrew python" \
+          brew link python
+      fi
+
+      do_progress_quiet "Installing Python virtualenv" \
+        pip install virtualenv
     fi
-
-    do_progress_quiet "Installing Python virtualenv" \
-      pip install virtualenv
+    if [[ ! -d "./venv/" ]]; then
+      do_progress_quiet "Setting up a python virtualenv" \
+        virtualenv ./venv/
+    fi
+    do_progress_quiet "Activating virtualenv" \
+      source ./venv/bin/activate
+  else
+    >&2 echo "Skipping virtualenv because already in one"
   fi
 fi
 
-[[ $(which node) ]] || die "ERROR: node (NodeJS) is not installed. Install it by going to https://github.com/creationix/nvm"
-
-
-
-# Install https://yarnpkg.com (package manager)
-if [[ -f "./package.json" && ! $(which yarn) ]]; then
-  # Prompt when on debian
-  if [[ $(which apt-key) ]]; then
-    read -p "Would you like to install yarn (y/N)? This will use sudo to install a 3rd party apt repository, and install the yarn package." choice
-    echo # Move to a new line
-    if [[ "${choice}" =~ ^[Yy]$ ]]; then
-      progress "Installing yarn. You may be prompted for a password"
-      curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - || exit 1
-      echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list || exit 1
-      sudo apt-get update && sudo apt-get install yarn || exit 1
-    else
-      die "ERROR: Yarn is not installed. To install yarn manually, follow the instructions at https://yarnpkg.com/en/docs/install#linux-tab"
+# Javascript environment
+if [[ -f "./package.json" ]]; then
+  [[ $(which yarn) ]] || die "ERROR: Install yarn by going to https://yarnpkg.com"
+fi
+if [[ -f "./.nvmrc" ]]; then
+  # Set up the correct version of node (Travis automatically does this)
+  if [[ ! "${CI}" = "true" ]]; then
+    if [[ ! -f ~/.nvm/nvm.sh ]]; then
+      die "ERROR: Install nvm by going to https://github.com/creationix/nvm"
     fi
-  else
-    die "Not sure how to install yarn automatically. If you are using macOS do you have https://brew.sh installed?. To install yarn manually, follow the instructions at https://yarnpkg.com"
+    source ~/.nvm/nvm.sh --no-use
+    do_progress_quiet "Setting correct node version (see ./.nvmrc)" \
+      nvm install $(< ./.nvmrc)
   fi
 fi
 
