:art: colors  and messages

diff --git a/script/build-pdf b/script/build-pdf
--- a/script/build-pdf
+++ b/script/build-pdf
@@ -3,20 +3,52 @@
 set -e
 cd "$(dirname "$0")/.."
 
-if [[ ! $1 ]]; then
-  echo "Try adding --help to get more information"
-  exit 1
-else
-  # Only activate the virtualenv if not already in one
-  [[ -z "${VIRTUAL_ENV}" ]] && source ./venv/bin/activate
+source ./script/bootstrap || exit 1
 
-  # The XML Catalogs on OSX are not in the default directory because they are installed via homebrew
-  if [[ $(which brew) ]]; then
-    XML_CATALOG_FILES=$(brew --prefix)/etc/xml/catalog python collectiondbk2pdf.py $1 $2 $3 $4 $5 $6 $7 $8 $9
-    exit $?
+if [[ ! $1 || ! -d "./data/$1/" ]]; then
+  if [[ -d "./data/" && $(ls ./data/) ]]; then
+    echo "A valid book name (directory in ./data/) needs to be specified. Valid options are:"
+    echo $(ls ./data/)
+    exit 1
   else
-    python collectiondbk2pdf.py $1 $2 $3 $4 $5 $6 $7 $8 $9
-    exit $?
+    die "No source files in ./data/ exist. Please unzip a complete zip and name it something that matches one of the ccap-* names (without the ccap- prefix)"
+  fi
+else
+
+  source_dir="./data/$1/"
+  template_name="ccap-$1"
+  pdf_name="./out/$1.pdf"
+  temp_dir="./out/$1-temp/"
+
+  # Check that the CSS file exists:
+  if [[ ! -f "./css/${template_name}.css" ]]; then
+    die "ERROR: ./css/${template_name}.css does not exist. The name provided is invalid."
+  fi
+
+  [[ -d "./out/" ]] || mkdir -p "./out/"
+  [[ -d "${temp_dir}" ]] || mkdir -p "${temp_dir}"
+
+  # Remove the PDF file if it already exists
+  [[ -f "${pdf_name}" ]] && rm "${pdf_name}"
+
+  do_progress_quiet "Compiling CSS file" \
+    ./script/build-css $1
+
+  do_progress_quiet "Building PDF from ${source_dir} (~5min. use DEBUG=true for progress)" \
+    ./script/_build-pdf -d "${source_dir}" -s "${template_name}" -t "${temp_dir}" $2 $3 "${pdf_name}"
+
+  progress "Adding CSS reference into XHTML file for debugging"
+  sed -ir "s|</head>|<link rel=\"stylesheet\" type=\"text/css\" href=\"../../css/ccap-$1.css\" /></head>|" "${temp_dir}/collection.xhtml"
+
+  _say "${c_green}Finished building PDF.${c_none} Opening now"
+  _say "You can also view the XHTML file used to generate the PDF at ${temp_dir}/collection.xhtml"
+  if [[ $(which open) ]]; then
+    open "${pdf_name}"
+  fi
+
+  if [[ $(which say) ]]; then
+    # there is a say bash function so we need to use the bin version
+    $(which say) "Put down your cocktail. $1 PDF is done."
   fi
 
 fi
diff --git a/script/setup b/script/setup
--- a/script/setup
+++ b/script/setup
@@ -3,60 +3,53 @@ set -e
 
 cd "$(dirname "$0")/.."
 
-./script/bootstrap || exit 1
+source ./script/bootstrap || exit 1
 
->&2 echo "==> Installing JavaScript Packages"
-if [[ $(which yarn) ]]; then
-  yarn install || exit 1
-else
-  >&2 echo "WARNING: Installing JS packages using npm instead of yarn."
-  npm install || exit 1
-fi
+# JavaScript stuff
+do_progress_quiet "Installing JavaScript Packages" \
+  yarn --prefer-offline
 
+# Python stuff
+if [[ -f "./requirements.txt" || -f "./setup.py" ]]; then
+  # Only activate the virtualenv if not already in one
+  if [[ -z "${VIRTUAL_ENV}" ]]; then
 
-# Only activate the virtualenv if not already in one
-if [[ -z "${VIRTUAL_ENV}" ]]
-then
-
-  # This is mostly for travis
-  if [[ -z "$(which virtualenv)" ]]
-  then
-    >&2 echo "==> Installing Python virtualenv (pip install virtualenv)"
-    pip install virtualenv
-  fi
-
-  >&2 echo "==> Setting up a python virtualenv"
-  virtualenv ./venv/
-  source ./venv/bin/activate
-else
-  >&2 echo "==> Skipping virtualenv because already in one"
-fi
-
-pip install -U pip
-
-if [[ -n "${VIRTUAL_ENV}" ]]
-then
-
-  if [[ -f ./requirements.txt ]]; then
-    >&2 echo "==> Installing python packages"
-    pip install -r ./requirements.txt
-  else
-    if [[ -f ./setup.py ]]; then
-      >&2 echo "==> Installing python packages from setup.py"
-      python setup.py install
-    else
-      >&2 echo "==> Skipping install of python packages"
+    # This is mostly for travis
+    if [[ -z "$(which virtualenv)" ]]; then
+      do_progress_quiet "Installing Python virtualenv (pip install virtualenv)" \
+        pip install virtualenv
     fi
+
+    do_progress_quiet "Setting up a python virtualenv" \
+      virtualenv ./venv/
+    do_progress_quiet "Activating virtualenv" \
+      source ./venv/bin/activate
+  else
+    >&2 echo "Skipping virtualenv because already in one"
   fi
 
+  do_progress_quiet "Upgrading python pip" \
+    pip install -U pip
 
-else
-  echo "ERROR. Not in a virtualenv"
-  exit 1
+  if [[ -n "${VIRTUAL_ENV}" ]]; then
+    if [[ -f ./requirements.txt ]]; then
+      do_progress_quiet "Installing python packages" \
+        pip install -r ./requirements.txt
+    else
+      if [[ -f ./setup.py ]]; then
+        do_progress_quiet "Installing python packages from setup.py" \
+          python setup.py install
+      fi
+    fi
+  else
+    echo "ERROR. Not in a virtualenv"
+    exit 1
+  fi
 fi
-
 
 if [[ ! -f ./lib/SaxonTransformWrapper.class ]]; then
-  >&2 echo "==> Compiling XSLT2 Java classes"
+  progress "Compiling XSLT2 Java classes"
   $(cd ./lib/ && javac -cp saxon9he.jar SaxonTransformWrapper.java)
 fi
+
+_say "${c_green}Successfully set up${c_none}"
