Revert "Merge branch 'diff-books' into illustrious.imp"
This reverts commit 617104f36c1f7d2a7b09bbea692de40c41dbe87f, reversing
changes made to 05ff86bc49aa2aebede1051dbafb8e0cc13fb530.

diff --git a/script/setup b/script/setup
--- a/script/setup
+++ b/script/setup
@@ -1,25 +1,30 @@
 #!/bin/bash
-cd "$(dirname "$0")/.." || exit 111
-source ./script/bootstrap || exit 111
+set -e
+
+cd "$(dirname "$0")/.."
+
+source ./script/bootstrap || exit 1
 
 # JavaScript stuff
-if [[ -f "./package.json" ]]; then
-  do_progress_quiet "Installing JavaScript Packages" \
-    yarn --prefer-offline
-fi
+do_progress_quiet "Installing JavaScript Packages" \
+  yarn --prefer-offline
 
 # Python stuff
 if [[ -f "./requirements.txt" || -f "./setup.py" ]]; then
 
-  [[ -n "${VIRTUAL_ENV}" ]] || die "Not in a virtualenv"
-  if [[ -f "./requirements.txt" ]]; then
-    do_progress_quiet "Installing python packages" \
-      pip install -r "./requirements.txt"
-  else
-    if [[ -f "./setup.py" ]]; then
-      do_progress_quiet "Installing python packages from setup.py" \
-        python setup.py install
+  if [[ -n "${VIRTUAL_ENV}" ]]; then
+    if [[ -f "./requirements.txt" ]]; then
+      do_progress_quiet "Installing python packages" \
+        pip install -r "./requirements.txt"
+    else
+      if [[ -f "./setup.py" ]]; then
+        do_progress_quiet "Installing python packages from setup.py" \
+          python setup.py install
+      fi
     fi
+  else
+    echo "ERROR. Not in a virtualenv"
+    exit 1
   fi
 fi
 
@@ -32,10 +37,6 @@ if [[ -f "./Gemfile" ]]; then
 fi
 
 
-# Load anything that is repo-specific
-if [[ -f "./script/_setup.sh" ]]; then
-  # shellcheck disable=SC1091
-  source ./script/_setup.sh || exit 111
-fi
+# Setup stuff that is custom to this repo
 
 _say "${c_green}Successfully set up${c_none}"
