:art: ensure bootstrap is generic

diff --git a/script/setup b/script/setup
--- a/script/setup
+++ b/script/setup
@@ -28,9 +28,14 @@ if [[ -f "./requirements.txt" || -f "./setup.py" ]]; then
   fi
 fi
 
+# Setup stuff that is custom to this repo
+
 if [[ ! -f ./lib/SaxonTransformWrapper.class ]]; then
   progress "Compiling XSLT2 Java classes"
   $(cd ./lib/ && javac -cp saxon9he.jar SaxonTransformWrapper.java)
 fi
+
+[[ $(which xmllint) ]] || die "ERROR: xmllint is not installed. Please install it first"
+
 
 _say "${c_green}Successfully set up${c_none}"
