:art: clean up the test output

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -1,32 +1,71 @@
 #!/bin/bash
 
-set -e
 cd "$(dirname "$0")/.."
 
 # https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
-green_color="\033[0;32m"
-yellow_color="\033[1;33m"
-no_color='\033[0m'
+if [[ $(tput colors) -ge 8 ]]; then
+  c_none=$(tput sgr0)
+  # c_black=$(tput setaf 0)
+  c_red=$(tput setaf 1)
+  c_green=$(tput setaf 2)
+  # c_brown=$(tput setaf 3)
+  c_blue=$(tput setaf 4)
+  c_purple=$(tput setaf 5)
+  # c_cyan=$(tput setaf 6)
+  # c_gray=$(tput setaf 7)
+  c_dark=$(tput setaf 8)
+  # c_lred=$(tput setaf 9)
+  # c_lgreen=$(tput setaf 10)
+  c_yellow=$(tput setaf 11)
+  # c_lblue=$(tput setaf 12)
+  # c_lpurple=$(tput setaf 13)
+  c_lcyan=$(tput setaf 14)
+  # c_white=$(tput setaf 15)
+fi
 
-say() {
-  echo -e "$1"
+say() { echo -e "$1"; }
+progress() { say "${c_blue}==>${c_none} ${c_yellow}$1${c_none}"; }
+# https://stackoverflow.com/a/25515370
+yell() { >&2 say "$0: $*"; }
+die() { yell "$1"; exit $2; }
+try() { "$@" || die "${c_red}cannot run $*${c_none}" 112; }
+
+do_progress() { progress "$1"; try $2 $3 $4 $5 $6 $7 $8 $9; }
+
+# Alternative that outputs only when an error occurs
+progress_quiet() { echo -e -n "${c_yellow}==>${c_none} $1 ... "; }
+try_quiet() {
+  _myout=$(mktemp -t 'stdout')
+  _myerr=$(mktemp -t 'stderr')
+  "$@" > ${_myout} 2> ${_myerr}
+  substatus=$?
+  if [[ ${substatus} != 0 ]]; then
+    cat ${_myout}
+    >&2 cat ${_myerr}
+    rm ${_myout} ${_myerr}
+    die "${c_red}ERROR: could not run $*${c_none}" ${substatus}
+  else
+    rm ${_myout} ${_myerr}
+  fi
+}
+ok_quiet() { say "${c_green}OK${c_none}"; }
+do_progress_quiet() {
+  progress_quiet "$1"
+  try_quiet $2 $3 $4 $5 $6 $7 $8 $9
+  ok_quiet
 }
 
-progress() {
-  say "${yellow_color}==> $1${no_color}"
-}
 
-progress 'Checking that we can fetch docbook-xsl from the XML catalog'
 if [[ $(which brew) ]]; then
   declare -x XML_CATALOG_FILES=$(brew --prefix)/etc/xml/catalog
 fi
-xsltproc --catalogs --nonet ./docbook-xsl/xhtml-1_1/docbook.xsl ./test-ccap/m-anatomy/index_auto_generated.cnxml 2> /dev/null > /dev/null || exit 1
+do_progress 'Checking that we can fetch docbook-xsl from the XML catalog' \
+  xsltproc --catalogs --nonet --noout ./docbook-xsl/xhtml-1_1/docbook.xsl ./test-ccap/m-anatomy/index_auto_generated.cnxml
 
+do_progress 'Building a test book "PDF"' \
+  ./script/build-pdf -d ./test-ccap/ -s ccap-physics -p ./script/_no-op-prince
 
-progress 'Building a test book "PDF"'
-./script/build-pdf -d ./test-ccap/ -s ccap-physics -p ./script/_no-op-prince || exit 1
+do_progress 'Compiling all CSS files' \
+  ./script/build-css
 
-progress 'Compiling CSS files'
-./script/build-css > /dev/null || exit 1
-
-say "🎉 ${green_color}PASSED:${no_color} It seems all the tests passed 🎈"
+say "${c_green}PASSED:${c_none} It seems all the tests passed 🎉"
